# Generated by Django 4.2.7 on 2024-01-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qst_number',
        ),
    ]
