# Generated by Django 4.2.7 on 2024-02-09 04:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizes', '0003_alter_quiz_deduct_marks_per_wrong_answer_and_more'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
    ]
