# Generated by Django 4.2.7 on 2024-02-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_remove_rating_created_at_remove_rating_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
    ]
