# Generated by Django 4.2.7 on 2024-02-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_remove_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
