# Generated by Django 4.2.7 on 2024-02-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_taken', '0002_alter_quiz_taken_quiz_name_alter_quiz_taken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_taken',
            name='score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
