# Generated by Django 4.2.7 on 2024-01-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('difficulty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('number_of_Questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='duration in minute')),
                ('required_to_pass', models.IntegerField(help_text='Percent marks to need pass')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='difficulty.difficulty')),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
    ]
