# Generated by Django 4.2.7 on 2024-01-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='deduct_marks_per_wrong_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='marks_per_right_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
