# Generated by Django 4.2.7 on 2024-01-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_quiz_deduct_marks_per_wrong_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='deduct_marks_per_wrong_answer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='marks_per_right_answer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
